### PR TITLE
Update PostCSS version

### PR DESCRIPTION
**Pull request by antyakushev**
This should be a major release since PostCSS API has changed

### CODE REVIEW

**Comment by seaneking** [comment]
Any update on this? Would be great to get merged in.

**Comment by Rycochet** [comment]
Doh sorry - not had much free time and forgot to get back to this.

@antyakushev Can you bump the patch version in package.json to 3.0.0 then I'll pull and update npm :-)

**Comment by antyakushev** [comment]
@Rycochet sure, done :-)

**Comment by Rycochet** [comment]
And published to npm - thanks @antyakushev :-)

**Pull request merged**
